import offer1 from "../assets/Group 8.png";
import offer2 from "../assets/Group 8 (2).png";
import offer3 from "../assets/Group 8 (1).png";

// Birthday Cakes
export const birthdayCakes = [
  {
    id: 1,
    name: "Red Velvet Hammer Pinata Cake – 500 g",
    title: "Red Velvet Hammer Pinata Cake",
    price: "₹1,100.00",
    sku: "24167",
    image: offer1,
    badge: "EGG LESS",
    badgeColor: "#00b53d",
    rating: 4.8,
    reviews: 45,
  },
  {
    id: 2,
    name: "Pineapple Hammer Pinata Cake – 500 g",
    title: "Pineapple Hammer Pinata Cake",
    price: "₹1,000.00",
    sku: "24166",
    image: offer2,
    badge: "EGG LESS",
    badgeColor: "#00b53d",
    rating: 4.7,
    reviews: 38,
  },
  {
    id: 3,
    name: "Chocolate Hammer Pinata Surprise Cake",
    title: "Chocolate Hammer Pinata Surprise",
    price: "₹1,000.00",
    sku: "24168",
    image: offer3,
    badge: "EGG LESS",
    badgeColor: "#00b53d",
    rating: 4.9,
    reviews: 52,
  },
  {
    id: 4,
    name: "Butterscotch Hammer Pinata Cake – 500 g",
    title: "Butterscotch Hammer Pinata Cake",
    price: "₹1,000.00",
    sku: "24169",
    image: offer1,
    badge: "EGG LESS",
    badgeColor: "#00b53d",
    rating: 4.6,
    reviews: 29,
  },
  {
    id: 5,
    name: "Choco-Fruit Fusion Cake – 1 Kg",
    title: "Choco-Fruit Fusion Cake",
    price: "₹1,850.00",
    sku: "24244",
    image: offer2,
    badge: "EGG LESS",
    badgeColor: "#00b53d",
    rating: 4.8,
    reviews: 41,
  },
];

// Beautiful Cakes
export const beautifulCakes = [
  {
    id: 1,
    name: "Teacher's Day Special Pineapple Cake",
    title: "Teacher's Day Special Pineapple",
    price: "₹850.00",
    sku: "26305",
    image: offer3,
    badge: "EGG LESS",
    badgeColor: "#00b53d",
    rating: 4.7,
    reviews: 33,
  },
  {
    id: 2,
    name: "Cake Chocolate Teacher's Day",
    title: "Chocolate Teacher's Day Cake",
    price: "₹850.00",
    sku: "26304",
    image: offer1,
    badge: "EGG LESS",
    badgeColor: "#00b53d",
    rating: 4.8,
    reviews: 28,
  },
  {
    id: 3,
    name: "Teacher's Day Special Butterscotch Cake",
    title: "Teacher's Day Butterscotch",
    price: "₹800.00",
    sku: "26303",
    image: offer2,
    badge: "EGG LESS",
    badgeColor: "#00b53d",
    rating: 4.6,
    reviews: 25,
  },
  {
    id: 4,
    name: "Labubu Chocolate Cake – 1 Kg",
    title: "Labubu Chocolate Cake",
    price: "₹1,800.00",
    sku: "30352",
    image: offer3,
    badge: "EGG LESS",
    badgeColor: "#00b53d",
    rating: 4.9,
    reviews: 67,
  },
  {
    id: 5,
    name: "Strawberry Bunny Cream Cake",
    title: "Strawberry Bunny Cream Cake",
    price: "₹825.00",
    sku: "20636",
    image: offer1,
    badge: "EGG LESS",
    badgeColor: "#00b53d",
    rating: 4.7,
    reviews: 44,
  },
];

// Hunger Bites (Sub Sandwiches)
export const hungerBites = [
  {
    id: 1,
    name: "Sub Paneer Tikka (6) - Danbro by Mr. Brown",
    title: "Sub Paneer Tikka (6)",
    price: "₹249.00",
    originalPrice: "₹299.00",
    sku: "862",
    image: offer2,
    discount: "17% OFF",
    rating: 4.6,
    reviews: 89,
  },
  {
    id: 2,
    name: "Sub Paneer Tikka (12) - Danbro by Mr. Brown",
    title: "Sub Paneer Tikka (12)",
    price: "₹480.00",
    originalPrice: "₹580.00",
    sku: "863",
    image: offer2,
    discount: "17% OFF",
    rating: 4.7,
    reviews: 76,
  },
  {
    id: 3,
    name: "Sub Golden Delight (6) - Danbro by Mr. Brown",
    title: "Sub Golden Delight (6)",
    price: "₹210.00",
    sku: "864",
    image: offer3,
    rating: 4.5,
    reviews: 62,
  },
  {
    id: 4,
    name: "Sub Golden Delight (12) - Danbro by Mr. Brown",
    title: "Sub Golden Delight (12)",
    price: "₹410.00",
    sku: "865",
    image: offer3,
    rating: 4.6,
    reviews: 54,
  },
  {
    id: 5,
    name: "Sub Exotic Veg (6) - Danbro by Mr. Brown",
    title: "Sub Exotic Veg (6)",
    price: "₹210.00",
    sku: "866",
    image: offer1,
    rating: 4.4,
    reviews: 48,
  },
];

// Creamless Cakes
export const creamlessCakes = [
  {
    id: 1,
    name: "Eggless Merry Berry Pineapple Celebration Cake",
    title: "Merry Berry Pineapple Cake",
    price: "₹800.00",
    sku: "30613",
    image: offer1,
    badge: "EGG LESS",
    badgeColor: "#00b53d",
    rating: 4.8,
    reviews: 56,
  },
  {
    id: 2,
    name: "Eggless Fresh Butterscotch New Year Cake 500g",
    title: "Fresh Butterscotch New Year",
    price: "₹800.00",
    sku: "22607",
    image: offer2,
    badge: "EGG LESS",
    badgeColor: "#00b53d",
    rating: 4.7,
    reviews: 43,
  },
  {
    id: 3,
    name: "Eggless Black Forest New Year Cake 500g",
    title: "Black Forest New Year Cake",
    price: "₹800.00",
    sku: "20831",
    image: offer3,
    badge: "EGG LESS",
    badgeColor: "#00b53d",
    rating: 4.9,
    reviews: 71,
  },
  {
    id: 4,
    name: "Rich Plum Cake (800g)",
    title: "Rich Plum Cake",
    price: "₹1,440.00",
    sku: "18931",
    image: offer1,
    badge: "EGG LESS",
    badgeColor: "#00b53d",
    rating: 4.8,
    reviews: 94,
  },
  {
    id: 5,
    name: "Plum Cake (800g)",
    title: "Plum Cake",
    price: "₹1,360.00",
    sku: "18929",
    image: offer2,
    badge: "EGG LESS",
    badgeColor: "#00b53d",
    rating: 4.7,
    reviews: 87,
  },
];

// Take me Along (Gift Items)
export const takeMeAlong = [
  {
    id: 1,
    name: "100 Roses Bunch - A Grand Expression of Love",
    title: "100 Roses Bunch",
    price: "₹4,000.00",
    sku: "19423",
    image: offer3,
    rating: 4.9,
    reviews: 125,
  },
  {
    id: 2,
    name: "15 Roses Bouquet - Elegant Expression of Love",
    title: "15 Roses Bouquet",
    price: "₹600.00",
    sku: "19418",
    image: offer1,
    rating: 4.7,
    reviews: 98,
  },
  {
    id: 3,
    name: "20 Roses Bunch - A Grand Gesture of Love",
    title: "20 Roses Bunch",
    price: "₹800.00",
    sku: "19419",
    image: offer2,
    rating: 4.8,
    reviews: 112,
  },
  {
    id: 4,
    name: "25 Roses Bunch - A Sweet Gesture of Love",
    title: "25 Roses Bunch",
    price: "₹1,000.00",
    sku: "19420",
    image: offer3,
    rating: 4.8,
    reviews: 105,
  },
];

// Fillers
export const fillers = [
  {
    id: 1,
    name: "Mushroom and Corn Patty | Veggie Delight",
    title: "Mushroom and Corn Patty",
    price: "₹60.00",
    sku: "706",
    image: offer1,
    rating: 4.5,
    reviews: 67,
  },
  {
    id: 2,
    name: "Patty Chilly Paneer | Paneer Treat",
    title: "Patty Chilly Paneer",
    price: "₹61.00",
    sku: "677",
    image: offer2,
    rating: 4.6,
    reviews: 54,
  },
  {
    id: 3,
    name: "Patty Paneer Puff | Flaky Puff",
    title: "Patty Paneer Puff",
    price: "₹60.00",
    sku: "236",
    image: offer3,
    rating: 4.5,
    reviews: 49,
  },
  {
    id: 4,
    name: "Red Sauce Pasta | Savory & Rich",
    title: "Red Sauce Pasta",
    price: "₹380.00",
    sku: "754",
    image: offer1,
    rating: 4.7,
    reviews: 82,
  },
  {
    id: 5,
    name: "Aloo Patty | Spicy Crispy Potato",
    title: "Aloo Patty",
    price: "₹40.00",
    sku: "721",
    image: offer2,
    rating: 4.4,
    reviews: 73,
  },
];

// Our Best Selling Products
export const bestSellingProducts = [
  {
    id: 1,
    name: "Baklawa Crunchy Pouch | Danbro by Mr. Brown",
    title: "Baklawa Crunchy Pouch",
    price: "₹695.00",
    sku: "3950",
    image: offer3,
    badge: "EGG LESS",
    badgeColor: "#00b53d",
    rating: 4.9,
    reviews: 156,
  },
  {
    id: 2,
    name: "Baklawa Roll Crunchy | Danbro by Mr. Brown",
    title: "Baklawa Roll Crunchy",
    price: "₹48.00",
    sku: "3937",
    image: offer1,
    badge: "EGG LESS",
    badgeColor: "#00b53d",
    rating: 4.8,
    reviews: 142,
  },
  {
    id: 3,
    name: "Chocolate Gujia (1Kg) | Danbro by Mr. Brown",
    title: "Chocolate Gujia (1Kg)",
    price: "₹1,160.00",
    sku: "1246",
    image: offer2,
    badge: "EGG LESS",
    badgeColor: "#00b53d",
    rating: 4.7,
    reviews: 128,
  },
  {
    id: 4,
    name: "Chocolate Gujia (500g) | Danbro by Mr. Brown",
    title: "Chocolate Gujia (500g)",
    price: "₹588.00",
    sku: "18193",
    image: offer3,
    badge: "EGG LESS",
    badgeColor: "#00b53d",
    rating: 4.8,
    reviews: 134,
  },
];
